import { type CSSProperties } from "react";

export const S: Record<string, CSSProperties> = {
  app: {
    background: "#0B0F14",
    minHeight: "100vh",
    color: "#E7E5E0",
    fontFamily: "'Inter', sans-serif",
    fontSize: 14,
  },
  tickerStrip: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    background: "#0F141B",
    borderBottom: "1px solid #232B36",
    padding: "8px 16px",
    overflow: "hidden",
    whiteSpace: "nowrap",
  },
  tickerScroll: { display: "flex", gap: 24, overflow: "hidden" },
  tickerItem: { display: "flex", gap: 6, fontFamily: "'IBM Plex Mono', monospace", fontSize: 12, flexShrink: 0 },
  body: { display: "flex", alignItems: "flex-start" },
  sidebar: {
    width: 320,
    flexShrink: 0,
    padding: "24px 20px",
    borderRight: "1px solid #232B36",
    position: "sticky",
    top: 0,
  },
  h1: { fontFamily: "'Space Grotesk', sans-serif", fontSize: 26, fontWeight: 700, lineHeight: 1.1, margin: "0 0 8px" },
  subtitle: { color: "#8892A0", fontSize: 12.5, lineHeight: 1.5, margin: "0 0 20px" },
  section: { marginBottom: 20 },
  sectionLabel: {
    fontFamily: "'IBM Plex Mono', monospace",
    fontSize: 11,
    letterSpacing: "0.08em",
    textTransform: "uppercase",
    color: "#FFB020",
    marginBottom: 10,
  },
  holdingRow: { display: "flex", alignItems: "center", gap: 6, marginBottom: 6, padding: "4px 4px", borderRadius: 6 },
  symbolInput: {
    flex: 1,
    background: "#131820",
    border: "1px solid #232B36",
    borderRadius: 6,
    color: "#E7E5E0",
    padding: "7px 8px",
    fontFamily: "'IBM Plex Mono', monospace",
    fontSize: 13,
    width: 0,
  },
  weightInput: {
    width: 56,
    background: "#131820",
    border: "1px solid #232B36",
    borderRadius: 6,
    color: "#E7E5E0",
    padding: "7px 6px",
    fontFamily: "'IBM Plex Mono', monospace",
    fontSize: 13,
    textAlign: "right",
  },
  pctSign: { color: "#8892A0", fontSize: 12, width: 10 },
  iconBtn: {
    background: "transparent",
    border: "none",
    color: "#8892A0",
    cursor: "pointer",
    padding: 4,
    display: "flex",
  },
  rowActions: { display: "flex", gap: 8, marginTop: 8, flexWrap: "wrap" },
  ghostBtn: {
    display: "flex",
    alignItems: "center",
    gap: 5,
    background: "transparent",
    border: "1px solid #2A3340",
    color: "#C4CBD4",
    borderRadius: 6,
    padding: "6px 10px",
    fontSize: 12,
    cursor: "pointer",
  },
  weightSumLine: { fontFamily: "'IBM Plex Mono', monospace", fontSize: 12, marginTop: 10 },
  fieldLabel: { display: "block", fontSize: 11.5, color: "#8892A0", marginTop: 10, marginBottom: 4 },
  fullInput: {
    width: "100%",
    background: "#131820",
    border: "1px solid #232B36",
    borderRadius: 6,
    color: "#E7E5E0",
    padding: "8px 9px",
    fontFamily: "'IBM Plex Mono', monospace",
    fontSize: 13,
  },
  checkboxLabel: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    fontSize: 12,
    color: "#8892A0",
    marginTop: 14,
    cursor: "pointer",
  },
  runBtn: {
    width: "100%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    background: "#FFB020",
    color: "#0B0F14",
    border: "none",
    borderRadius: 7,
    padding: "12px 0",
    fontWeight: 600,
    fontSize: 14,
    cursor: "pointer",
    marginTop: 6,
  },
  errorBox: { display: "flex", alignItems: "center", gap: 6, color: "#F2545B", fontSize: 12.5, marginTop: 10 },
  main: { flex: 1, padding: "24px 28px", minWidth: 0 },
  emptyState: { textAlign: "center", color: "#8892A0", padding: "100px 40px", maxWidth: 460, margin: "0 auto" },
  emptyGlyph: { fontSize: 28, color: "#FFB020", marginBottom: 14 },
  banner: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    background: "#1A1607",
    border: "1px solid #4A3A10",
    color: "#E7C77A",
    borderRadius: 8,
    padding: "10px 14px",
    fontSize: 12.5,
    marginBottom: 18,
    lineHeight: 1.5,
  },
  metricGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(140px, 1fr))",
    gap: 10,
    marginBottom: 22,
  },
  metricCard: { background: "#131820", border: "1px solid #232B36", borderRadius: 8, padding: "12px 14px" },
  metricLabel: { fontSize: 11, color: "#8892A0", marginBottom: 6, textTransform: "uppercase", letterSpacing: "0.03em" },
  metricValue: { fontFamily: "'IBM Plex Mono', monospace", fontSize: 19, fontWeight: 600 },
  panel: {
    background: "#101520",
    border: "1px solid #232B36",
    borderRadius: 10,
    padding: "16px 18px",
    marginBottom: 18,
  },
  panelTitle: {
    fontFamily: "'Space Grotesk', sans-serif",
    fontSize: 14.5,
    fontWeight: 600,
    marginBottom: 12,
    color: "#E7E5E0",
  },
  twoCol: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 18 },
  tooltip: { background: "#131820", border: "1px solid #2A3340", borderRadius: 6, fontSize: 12 },
  table: { width: "100%", borderCollapse: "collapse", fontFamily: "'IBM Plex Mono', monospace", fontSize: 12.5 },
  th: { textAlign: "center", color: "#8892A0", fontWeight: 500, padding: "6px 8px", borderBottom: "1px solid #232B36" },
  thLeft: {
    textAlign: "left",
    color: "#8892A0",
    fontWeight: 500,
    padding: "6px 8px",
    borderBottom: "1px solid #232B36",
  },
  thCorner: { padding: "6px 8px", borderBottom: "1px solid #232B36" },
  td: { textAlign: "center", padding: "7px 8px", borderBottom: "1px solid #1A2029" },
  tdLeft: { textAlign: "left", padding: "7px 8px", borderBottom: "1px solid #1A2029" },
  corrCell: { textAlign: "center", padding: "7px 8px", borderBottom: "1px solid #1A2029", borderRadius: 3 },
  inlineIcon: { verticalAlign: "-1px", marginRight: 2 },
};
